name: tourist_backend_dart_frog
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  json_annotation: ^4.8.1
  mongo_dart: ^0.9.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
